name: Build API Docker image

on:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push image to GHCR'
        required: false
        default: 'false'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event.inputs.push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        uses: docker/build-push-action@v5
        with:
          context: apps/api
          file: apps/api/Dockerfile
          push: ${{ github.event.inputs.push == 'true' }}
          tags: ghcr.io/${{ github.repository_owner }}/autoescola-api:latest
          load: false

      - name: Railway deploy (optional)
        if: secrets.RAILWAY_TOKEN != ''
        run: |
          echo "Railway deploy token detected. Configure deployment steps here."
